# Generated by Django 5.1.1 on 2025-02-24 13:54

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_remove_quiz_sub_category_alter_quiz_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
