# Generated by Django 5.1.1 on 2025-02-12 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comment',
            table='comments',
        ),
        migrations.AlterModelTable(
            name='follower',
            table='followers',
        ),
        migrations.AlterModelTable(
            name='like',
            table='likes',
        ),
        migrations.AlterModelTable(
            name='rating',
            table='ratings',
        ),
    ]
