# Generated by Django 5.1.1 on 2025-02-17 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0005_alter_like_unique_together_commentlike_dislike_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follower',
        ),
    ]
