# Generated by Django 5.1.1 on 2025-02-12 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attempts', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='quizattempt',
            table='quiz_attempts',
        ),
        migrations.AlterModelTable(
            name='userresponse',
            table='user_responses',
        ),
    ]
